version: '2'

services:
  redis:
    container_name: redis
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - '5341:80'
    volumes:
      - 'seq_data:/data'
    environment:
      - ACCEPT_EULA=Y

volumes:
  seq_data:
    driver: local
  redis_data:
    driver: local