version: "2"

services:
  redis:
    container_name: redis
    image: "docker.io/bitnami/redis:6.0-debian-10"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - "redis_data:/bitnami/redis/data"
    networks:
      - smew_default

  redisinsight:
    container_name: redisinsight
    image: "redislabs/redisinsight:latest"
    ports:
      - "8001:8001"
    volumes:
      - "redisinsight_data:/db"
    networks:
      - smew_default

  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    volumes:
      - "seq_data:/data"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - smew_default

  api:
    build:
      context: ./SmewApi
      args:
        - SmewApi__Redis__ConnectionString=redis
        - SmewApi__Serilog__WriteTo__0__Args__serverUrl=seq:5341
    image: smewapi:latest
    container_name: smewapi
    ports:
      - 5001:8080
    depends_on:
      - redis
      - seq
    networks:
      - smew_default

volumes:
  seq_data:
    driver: local
  redis_data:
    driver: local
  redisinsight_data:
    driver: local

networks:
  smew_default:
